### PR TITLE
Bug #34: InvalidCastException is raised when using AssemblyRunner

### PR DESCRIPTION
**Pull request by AlexeyZarubin**
1) Fix an issue by adding an AssemblyResolve to find a missing xunit libraries.

### CODE REVIEW

**Comment by jsdbroughton** [comment]
This has been hanging for a long time, I know these issues/PRs haven't migrated to Jira. cc @BovineOx, @connorivy

**Comment by bimgeek** [comment]
I have created a ticket to review this as part of our next sprint.

**Comment by BovineOx** [comment]
@AlexeyZarubin apologies for the delay in looking into this, we have a number of repos and are looking for improvements to visibility about PRs being raised externally on them.

**Review by connorivy — APPROVED** [review]
Hey @AlexeyZarubin 

Thanks for the PR, looks good to me

**Pull request merged**
